name: CI

on:
  push

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: cd development/tomcoakes/bouncing-balls-with-canvas/ && git pull && npm install && npm run build && pwd && ls -al && npm start
